# Setup
title:               Славелий Роза
tagline:             'Весь как есть'
description:         'Блог и немного информации'
url:                 https://utkorose.ru
baseurl:             ''
paginate:            5
permalink:           /:title

# About/contact
author:
  name:              Славелий Роза
  url:               https://twitter.com/utkorose
  email:             utkorose@yandex.ru

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
